Improve hot-sauce and install more packages

diff --git a/slay b/slay
--- a/slay
+++ b/slay
@@ -67,6 +67,19 @@ ask_for_sudo
 # ssh_key_setup
 
 ###############################################################################
+# INSTALL: Customizations
+###############################################################################
+chapter "Adding hot sauce…"
+
+if [ -e $cwd/bag/hot-sauce ]; then
+	cd "$(dirname "${BASH_SOURCE[0]}")" \
+		&& . "$cwd/bag/hot-sauce"; printf "\n"; print_in_green "  [✓] "; printf "You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
+else
+	printf "\n ⚠️  $cwd/bag/hot-sauce not found\n"
+	exit 1
+fi
+
+###############################################################################
 # INSTALL: Dependencies
 ###############################################################################
 chapter "Installing Dependencies…"
@@ -85,18 +98,6 @@ fi
 
 if [ ! -d "$HOME/.bin/" ]; then
 	mkdir "$HOME/.bin"
-fi
-
-# -----------------------------------------------------------------------------
-# Bash-it
-# -----------------------------------------------------------------------------
-if [ -d "$HOME/.bash_it" ]; then
-	print_success_muted "Bash-it already installed. Skipping."
-else
-	step "Installing Bash-it…"
-	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
-	~/.bash_it/install.sh --silent --no-modify-config
-	print_success "Bash-it installed!"
 fi
 
 # -----------------------------------------------------------------------------
@@ -205,21 +206,6 @@ if [ -e $cwd/swag/npm ]; then
 		VALUE="${pkg##*::}"
 		install_npm_packages $KEY $VALUE
 	done
-fi
-
-
-###############################################################################
-# OPTIONAL: Customizations
-###############################################################################
-chapter "Adding hot sauce…"
-if [ -f "$HOME/.hot-sauce" ]; then
-	if ask "Do you want to add hot sauce?" Y; then
-		. "$HOME/.hot-sauce"; printf "\n  You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
-	else
-		print_success_muted "Hot sauce declined. Skipped.";
-	fi
-else
-	print_warning "No ~/.hot-sauce found. Skipping."
 fi
 
 ###############################################################################
