WIP: Improve VSCode config (still needs work)

diff --git a/bag/hot-sauce b/bag/hot-sauce
--- a/bag/hot-sauce
+++ b/bag/hot-sauce
@@ -75,21 +75,23 @@ step "Creating git aliases"
 create_git_aliases
 
 step "Configuring vscode…"
+if [ -e "$cwd/bag/vscode/helper_functions" ]; then
+    cd "$(dirname "${BASH_SOURCE[0]}")" \
+        && . "$cwd/bag/vscode/helper_functions"
+else
+    printf "\n ⚠️  $cwd/bag/vscode/helper_fuctions not found. Aborting…\n"
+    exit 1
+fi
+
 if [ -d "$HOME/Library/Application Support/Code - Insiders" ]; then
     print_muted "${indent} Code Insiders installation found."
 
-    code-insiders --install-extension shan.code-settings-sync
-    cp "$cwd/bag/vscode/settings.json" "$HOME/Library/Application Support/Code - Insiders/User/"
-
-    print_in_green "${indent} Code Insiders configured."
+    configure_vscode_insiders
 else
     if [ -d "$HOME/Library/Application Support/Code" ]; then
         print_muted "${indent} Code installation found."
 
-        code --install-extension shan.code-settings-sync
-        cp "$cwd/bag/vscode/settings.json" "$HOME/Library/Application Support/Code/User/"
-
-        print_in_green "${indent} Code configured."
+        configure_vscode
     else
         print_muted "${indent} No VSCode installation found. Please install vscode manually and try again. Skipping."
     fi
